name: my-first-workflow
on: [push]
jobs:
  runs-on: ubuntu-latest
  steps:
    - name: check out the repository
    - uses: actions/checkout@v2 
    
    - name: run a message
      run: echo 'workflow executed successfully'
    
